{% set version = "1.5.0" %}

package:
  name: contextily
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/contextily/contextily-{{ version }}.tar.gz
  sha256: 295b2d8097f8f6e80e1cb5e6e77538d1cdf729f827ec54eedc57f613c0a3ce0e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >=3.8
    - geopy
    - joblib
    - matplotlib-base
    - mercantile
    - pillow
    - rasterio
    - requests
    - xyzservices

test:
  imports:
    - contextily
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geopandas/contextily
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Context geo-tiles in Python
  license_family: BSD

extra:
  recipe-maintainers:
    - darribas
    - ocefpaf
    - jorisvandenbossche
    - ljwolf
    - martinfleis
