{% set version = "1.3.0" %}

package:
  name: contextily
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/contextily/contextily-{{ version }}.tar.gz
  sha256: 3428aedbd4a7e3e1f6caf56f578d7685469072b5bd7541d92e4b54751d51163a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - geopy
    - joblib
    - matplotlib-base
    - mercantile
    - pillow
    - rasterio
    - requests
    - xyzservices

test:
  imports:
    - contextily
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geopandas/contextily
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Context geo-tiles in Python
  license_family: BSD

extra:
  recipe-maintainers:
    - darribas
    - ocefpaf
    - jorisvandenbossche
    - ljwolf
