{% set version = "1.6.2" %}

package:
  name: contextily
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/contextily/contextily-{{ version }}.tar.gz
  sha256: 3c747925269be248a9b1a761859e05d1681286e04d5d0796bdaf1de3409474bb

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - geopy
    - joblib
    - matplotlib-base
    - mercantile
    - pillow
    - rasterio
    - requests
    - xyzservices

test:
  imports:
    - contextily
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/geopandas/contextily
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Context geo-tiles in Python
  license_family: BSD

extra:
  recipe-maintainers:
    - darribas
    - ocefpaf
    - jorisvandenbossche
    - ljwolf
    - martinfleis
