{% set version = "0.9.2" %}

package:
  name: contextily
  version: {{ version }}

source:
  fn: contextily-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/contextily/contextily-{{ version }}.tar.gz
  sha256: 3834eb3f11f9e5c7a0a975a7206b84d1cdac5066c9d157d89dba50b8ca8719cb

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cartopy
    - pandas
    - pillow
    - rasterio
    - six
    - mercantile

test:
  imports:
    - contextily

about:
  home: https://github.com/darribas/contextily
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Context geo-tiles in Python.'
  license_family: BSD

extra:
  recipe-maintainers:
    - darribas
    - ocefpaf
