{% set version = "1.2.0" %}

package:
  name: contextily
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/contextily/contextily-{{ version }}.tar.gz
  sha256: 234705b3f03dfa1fcb5fabe765a4a7f72be91dafe2a6e18df270be391ae355dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - geopy
    - joblib
    - matplotlib-base
    - mercantile
    - pillow
    - rasterio
    - requests

test:
  imports:
    - contextily

about:
  home: https://github.com/geopandas/contextily
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Context geo-tiles in Python
  license_family: BSD

extra:
  recipe-maintainers:
    - darribas
    - ocefpaf
    - jorisvandenbossche
    - ljwolf
